version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  server:
    container_name: segui-app-server
    restart: on-failure
    depends_on:
      - mongo
    build: ./server/.
    ports:
      - "4400:4400"
      - "4401:4401"
    links:
      - mongo
  client:
    container_name: segui-app-client
    restart: on-failure
    depends_on:
      - server
    build: ./client/.
    ports:
      - "3000:3000"
    links:
      - server
